language: python
dist: bionic
os: linux

python:
  - "2.7"
  - "3.8"

compiler:
  - gcc

cache:
  apt: true

git:
  depth: 10

branches:
  only:
  - master

install:
  - pip install flake8

addons:
  apt:
    packages:
    - git
    - build-essential
    - automake
    - libtool
    - python-dev
    - gettext
    - swig

script:
  - flake8 --version
  - echo compiling AutoBouquetsMaker enigma2 plugin
  - python -m compileall .
  - find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
  - flake8 --ignore=W191,E128,E501,E722 . --exit-zero
  - echo done.

# PEP8 :- IGNORE CODES
# W191 : indentation contains tabs
# E128 : continuation line under-indented for visual indent
# E501 : line too long (> 79 characters)
# E722 : do not use bare 'except'

