language: python

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - git
    - build-essential
    - automake
    - libtool
    - python-dev
    - gettext
    - swig

python:
  - "2.7"

git:
  depth: 1

script:
- echo compiling AutoBouquetsMaker enigma2 plugin
- python -m compileall .
- echo done!
